name: Docker Image CI -consumer

on:
  push:
    branches:
      - 'main'
    paths:
      - '**.py'

jobs:
  editconfig:
    runs-on: ubuntu-latest
    steps:
      - name: EditorConfig-Action
        uses: zbeekman/EditorConfig-Action@v1.1.1

  linter:
    runs-on: ubuntu-latest
    steps:
      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2

  azurebuild:
    needs: [editconfig, linter]
    runs-on: ubuntu-latest

    steps:
      - name: Azure Login
      - uses: azure/login@v1
        with:
          creds: ${{ secrets.AZURE_CREDENTIALS }}
      - name: Azure Container Apps Build and Deploy
        uses: Azure/container-apps-deploy-action@v2
        with:
          containerAppName: consumer-test
          resourceGroup: fervjestina
          imageToDeploy: 1.labos/consumer
          acrname: containervjestina
